import React from "react";

    function Highlights({}) {
      return (<section className="highlights">
      <div>
        <h2>Specials</h2>
        <a href="#" role="button">Online Menu</a>
      </div>
      <div>
      <article>
            <img src="" alt="" />
            <h3>Appetizers</h3>
            <p>$1200</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A et earum accusamus odio tenetur, blanditiis totam alias vel, accusantium dicta consectetur sunt iste mollitia similique modi unde autem nulla maxime suscipit at. Natus ullam eius unde? Dolor, fugit. Maxime, commodi suscipit nulla ipsam aut ad? Similique ullam rem et necessitatibus!</p>
            <a href="#">Order Online <span>icon</span></a>
        </article>
      </div>
      </section>);
    }
  
  